### ISSUE TITLE
add highway shields

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#10]
currently we have none

**Comment by mojodna** [comment]
I did some work on this in the CaliParks map that could be improved / repurposed:

https://github.com/stamen/parks-forward-map/blob/master/sql/highway_shields.sql
https://github.com/stamen/parks-forward-map/blob/master/map.mss#L640-L690

(There are also versions for VT and OR on different branches.)

**Comment by almccon** [comment]
At minimum it would be a shame to lose the three types of shield we have now: Interstate, US, and California.
![screen shot 2015-08-24 at 4 07 21 pm](https://cloud.githubusercontent.com/assets/1212178/9454896/8fe8c912-4a7a-11e5-9264-ef7699e124c1.png)

If we fall back to rectangles everywhere else, that's okay. 

![screen shot 2015-08-24 at 4 09 29 pm](https://cloud.githubusercontent.com/assets/1212178/9454902/a2fe800a-4a7a-11e5-96b3-3334fd49fba0.png)

Or maybe we just enable VT and OR too, if we can pull from CaliParks.

**Comment by clhenrick** [comment]
cartocss reference: https://github.com/mapbox/carto/blob/master/docs/latest.md#shield

**Comment by clhenrick** [comment]
also Dane gives good advice here: http://gis.stackexchange.com/questions/47985/tilemill-label-and-shield-are-overlapping-how-can-this-be-solved

**Comment by clhenrick** [comment]
cascadenik code for previous shield placement is here: https://github.com/Citytracking/Terrain/blob/master/mapnik/routes.mss#L1-L74

**Comment by clhenrick** [comment]
@almccon @mojodna looks like in the og terrain that data generated from skeletron was used to render highway shields. Some [fancy pg regex](https://github.com/Citytracking/Terrain/blob/master/mapnik/skeletron.pgsql) was then used to get the appropriate text to place on top of the shields as well as to create categories for displaying the correct shield png file. 

Any ideas for how we might replicate this? I assume we will want to avoid any heavy data processing, ie: running skeletron for the whole OSM planet file.

**Comment by mojodna** [comment]
This is how I did it for the CaliParks map:

https://github.com/stamen/parks-forward-map/blob/master/sql/highway_shields.sql

https://github.com/stamen/parks-forward-map/blob/master/map.mss#L640-L690

**Comment by clhenrick** [comment]
adding the hwy shield layer to project.yml similarly to how it was done here: https://github.com/stamen/parks-forward-map/blob/master/project.yml#L727-L746

**Comment by clhenrick** [comment]
First pass at adding highway shields, so far so good:
![screen shot 2015-09-07 at 12 19 57 pm](https://cloud.githubusercontent.com/assets/161748/9720356/4af65932-555b-11e5-877c-109b5170bfcd.png)

![screen shot 2015-09-07 at 12 20 14 pm](https://cloud.githubusercontent.com/assets/161748/9720365/575da310-555b-11e5-9c40-5c1e66ee8501.png)

**To get an idea of what the non-CA state shields may look like:**
![screen shot 2015-09-07 at 12 23 13 pm](https://cloud.githubusercontent.com/assets/161748/9720373/6d155f5e-555b-11e5-8483-ed854066d888.png)

I'm also using the SVG icons when possible as they scale nicer / don't get pixellated. Will look into PNG icons for the other states once I've grabbed another OSM extract (eg: PDX)

**Comment by almccon** [comment]
Looking really good. Any idea what's happening with those odd drop-shadows around the non-CA shields? Are those svg rectangles?

**Comment by almccon** [comment]
Also, at the lower zooms (11 and 12) OG Terrain avoids showing shields for non-motorways. That avoids the situation in your first screenshot where you can't really see the road for CA-1 in Marin.

Actually, OG does something cutesy at zoom 12 with tiny, unlabeled California shields, but I don't think we need to bother replicating that.
![screen shot 2015-09-07 at 7 sep 4 25 11](https://cloud.githubusercontent.com/assets/1212178/9723721/054cb832-557d-11e5-9cca-6d174f2a1bb0.png)

**Comment by almccon** [comment]
Oh, actually, I'm wrong. Here is a case at z11 where it shows shields on highway 17 to Santa Cruz, even though it's not a motorway. Hmm, so I don't actually know what it's doing at that zoom. 

![screen shot 2015-09-07 at 7 sep 4 26 00](https://cloud.githubusercontent.com/assets/1212178/9723735/3b9e4342-557d-11e5-90fa-186f9c12ab6e.png)

**Comment by clhenrick** [comment]
@almccon not sure about the drop shadows around the rectangle shields. Those are actually png files and not SVGs. Perhaps it makes sense to make a rectangle SVG icon for the default shield?

**Comment by almccon** [comment]
Yeah, probably. I bet the drop shadows are really just an aliasing artifact where the edges of the png not aligning well with rendered pixels. An SVG rectangle should solve that.

**Comment by almccon** [comment]
Trying to run this locally, and it seems like there's a `highway_shields` table in the database that's not getting created for me.

https://github.com/stamen/terrain-classic/blob/master/terrain-classic.yml#L914

**Comment by clhenrick** [comment]
Hey Alan, you need to run the SQL in `sql/highway_shields.sql` to generate that table. I was not sure how to add running that SQL code to the Makefile.

**Comment by clhenrick** [comment]
- [ ] create default shield in SVG format

**Comment by clhenrick** [comment]
@almccon the default SVG shield rendering, okay to close this one?

![screen shot 2015-09-14 at 8 01 43 pm](https://cloud.githubusercontent.com/assets/161748/9864870/651fb71a-5b1c-11e5-8466-000169c3ffc9.png)

**Comment by almccon** [comment]
Yup, looks good to me!
