### ISSUE TITLE
add airports

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#11]
![screen shot 2015-06-26 at 6 19 06 pm](https://cloud.githubusercontent.com/assets/1212178/8389863/dbbe8cba-1c2f-11e5-8ad8-1248bd29cf11.png)

**Comment by clhenrick** [comment]
in the previous terrain icons for airports were added as follows:
https://github.com/Citytracking/Terrain/blob/master/mapnik/labels.mss#L25-L151

**Comment by clhenrick** [comment]
fixed.
![screen shot 2015-08-31 at 4 15 05 pm](https://cloud.githubusercontent.com/assets/161748/9589326/7d498e82-4ffb-11e5-86b5-59c94ae513e1.png)
