### ISSUE TITLE
Missing Tiles in France

### ISSUE THREAD

**Issue by AgenceStudiOne** [stamen/terrain-classic#111]
There are missing tiles in south of France : 

`<iframe width="600" height="420" src="http://maps.stamen.com/terrain/embed#15/42.7795/2.9115"></iframe>`

12067.png:1 GET http://d.tile.stamen.com/terrain/15/16648/12067.png 404 (Not Found)
12068.png:1 GET http://a.tile.stamen.com/terrain/15/16648/12068.png 404 (Not Found)
12067.png:1 GET http://c.tile.stamen.com/terrain/15/16647/12067.png 404 (Not Found)
12067.png:1 GET http://a.tile.stamen.com/terrain/15/16649/12067.png 404 (Not Found)
12068.png:1 GET http://d.tile.stamen.com/terrain/15/16647/12068.png 404 (Not Found)
12068.png:1 GET http://b.tile.stamen.com/terrain/15/16649/12068.png 404 (Not Found)
12067.png:1 GET http://d.tile.stamen.com/terrain/15/16648/12067.png 404 (Not Found)
12067.png:1 GET http://a.tile.stamen.com/terrain/15/16649/12067.png 404 (Not Found)
12068.png:1 GET http://a.tile.stamen.com/terrain/15/16648/12068.png 404 (Not Found)
12068.png:1 GET http://b.tile.stamen.com/terrain/15/16649/12068.png 404 (Not Found)
12067.png:1 GET http://b.tile.stamen.com/terrain/15/16650/12067.png 404 (Not Found)
12068.png:1 GET http://d.tile.stamen.com/terrain/15/16647/12068.png 404 (Not Found)
12068.png:1 GET http://c.tile.stamen.com/terrain/15/16650/12068.png 404 (Not Found)
12067.png:1 GET http://c.tile.stamen.com/terrain/15/16647/12067.png 404 (Not Found)
24135.png:1 GET http://c.tile.stamen.com/terrain/16/33299/24135.png 404 (Not Found)
24136.png:1 GET http://d.tile.stamen.com/terrain/16/33299/24136.png 404 (Not Found)

and the result : 

![terrain_umdj6ac_m4s](https://user-images.githubusercontent.com/48024521/53426916-31ab0c00-39e8-11e9-911a-040771bab1b0.jpeg)

**Comment by loganwilliams** [comment]
Duplicate #105
