### ISSUE TITLE
Create terrain-classic-lines and terrain-classic-background variants

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#14]
Currently I've got `terrain-classic` (which includes everything) and `terrain-classic-labels` as the only two variants. We also need `terrain-classic-lines` and `terrain-classic-background` (which omits labels and lines). 

Look at https://github.com/stamen/toner-carto to see how this is done. Also, compare `terrain-classic.yml` and `terrain-classic-labels.yml` in this repo, and extend the pattern to the other two variants. Also examine the `tessera.json` file in this repo to see how we serve up the variants.

For comparison, here are what the deployed styles look like:
http://maps.stamen.com/terrain-background/#13/37.7625/-122.3973
http://maps.stamen.com/terrain-labels/#13/37.7625/-122.3973
http://maps.stamen.com/terrain-lines/#13/37.7625/-122.3973

**Comment by clhenrick** [comment]
@almccon I'm not seeing `terrain-classic-labels` in the makefile to generate the corresponding xml file. When I run `make [terrain-classic-labels]` I get the following output:

`make: *** No rule to make target `[terrain-classic-labels]'.  Stop.`

**Comment by almccon** [comment]
Are you actually using those brackets around the make target? `make terrain-classic-labels` should work, but not `make [terrain-classic-labels]`. 

The reason there's not `terrain-classic-labels` in the Makefile is because magic. It hits the `%` wildcard which tries to make a `%.mml` file.... and that triggers the `%.yml` wildcard... so as long as `terrain-classic-labels.yml` exists, then `make terrain-classic-labels` should work.

**Comment by clhenrick** [comment]
Need to create the following YML files:

- [ ] terrain-classic-lines.yml
- [ ] terrain-classic-background.yml
