### ISSUE TITLE
add Admin 1 labels

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#16]
Seems like we should be able to easily port these from Toner? Though perhaps it depends on how we address the dymo placement of labels (ref #4)
![screen shot 2015-08-27 at 11 27 10 am](https://cloud.githubusercontent.com/assets/161748/9524784/b169ab5c-4cae-11e5-9415-d9714be95105.png)

**Comment by clhenrick** [comment]
We should include admin1 labels for the rest of the world where they are available from Natural Earth.

**Comment by clhenrick** [comment]
Admin1 labels also show up along borders:
![screen shot 2015-09-01 at 10 03 14 am](https://cloud.githubusercontent.com/assets/161748/9606339/e03a2d72-5090-11e5-9aef-26214d26ab2e.png)

**Comment by clhenrick** [comment]
@almccon @mojodna perhaps we can take a similar approach to the solution for city labels? Instead of using Aries data we could create centroids from natural earth admin1 data for global coverage and let Mapnik do the rendering. Let me know what you think.

**Comment by clhenrick** [comment]
I'm running into an issue when attempting to render centroids from `ne_10m_admin1_states_provinces` polygons; simply creating centroids will create multiple points for every polygon that is part of a state / province when we probably want only one that is in a central location and contained inside the largest polygon for a given state / province. 

Thinking there must be a way to do this with SQL but haven't figured it out yet.

**Comment by almccon** [comment]
Try the label points file from Natural Earth? http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-cultural-building-blocks/

**Comment by clhenrick** [comment]
I checked it out and it's like they took the regular states / provinces polygon file and did `ST_Centroid` on it, so lots of duplicate points.

**Comment by almccon** [comment]
Bummer. Although, did you check to see if there's a scalerank column or something similar? They might have left those duplicate points in there for use when you're really zoomed in, but NE generally is pretty good at letting you filter out irrelevant stuff if you want a zoomed-out map.

**Comment by clhenrick** [comment]
Not much better, this is filtering them to zoom 2 in QGIS:
![screen shot 2015-09-07 at 9 50 45 pm](https://cloud.githubusercontent.com/assets/161748/9724746/a380f676-55aa-11e5-9d28-1ebf4371714a.png)

**Comment by almccon** [comment]
That's very weird. I poked around in that file, and it looks like `adm0_sr` works better. But I'm not sure why the column is named that... "sr" sounds like it's another scale rank but why adm0 when these are adm1?

![screen shot 2015-09-07 at 7 sep 8 12 30](https://cloud.githubusercontent.com/assets/1212178/9725682/e7be0a30-559c-11e5-9623-b2f9f5b885cb.png)

**Comment by clhenrick** [comment]
Some other things I've tried:

**1. Creating a centroid for each state / province's set of points:**

```sql
create table ne_10m_admin_1_label_points_centroids as (
  SELECT name, admin, scalerank, st_centroid(st_union(geometry)) as geometry 
  FROM ne_10m_admin_1_label_points 
  WHERE scalerank < 3
  AND admin ilike 'united states of am%'
  GROUP BY name, admin, scalerank
  order by admin, name
);
```

But this gives some odd results with points not in the central location of a state / province.

**2. Pulling out the largest polygon for each state province and then creating a centroid for it:**

```sql
SELECT area, name, ST_Centroid(geom) geom
FROM ne_10m_admin_1_states_provinces
WHERE area IN (
      SELECT area
      FROM ne_10m_admin_1_states_provinces 
      WHERE name = 'state province name' 
      ORDER BY area DESC
      LIMIT 1
)
```

So far the above query works for a single state province. I need to figure out how to iterate over every state / province's set of polygons so [posted a question on gis stack exchange.](http://gis.stackexchange.com/questions/162162/postgis-query-to-retrieve-the-largest-polygon-for-multi-polygons-by-grouping-on)

**Comment by clhenrick** [comment]
Update, using modified query from above I was able to get the following results which I filtered on scalerank < 4:

![screen shot 2015-09-08 at 11 15 18 am](https://cloud.githubusercontent.com/assets/161748/9739255/e9192be6-561c-11e5-8d2f-5600bb0a1138.png)

**Comment by clhenrick** [comment]
So I've got the admin1 labels working for both N. America and elsewhere. At lower zooms (4&5) I'm using the original admin1 labels because they contain the state abbreviations. Then at zoom 6 the labels switch to the new admin1 label data. At zoom 5 the rest of the world has admin1 labels start to show up.
![screen shot 2015-09-08 at 3 07 32 pm](https://cloud.githubusercontent.com/assets/161748/9744762/c68192a2-563b-11e5-943e-459c59a3acf2.png)
![screen shot 2015-09-08 at 3 07 54 pm](https://cloud.githubusercontent.com/assets/161748/9744763/c91b5ef8-563b-11e5-85a0-1765381b6e20.png)
![screen shot 2015-09-08 at 3 08 04 pm](https://cloud.githubusercontent.com/assets/161748/9744769/cf2701bc-563b-11e5-85a0-7568bb509b50.png)
![screen shot 2015-09-08 at 3 10 15 pm](https://cloud.githubusercontent.com/assets/161748/9744773/d7189c82-563b-11e5-94bc-9ac596b4933d.png)

**Comment by almccon** [comment]
At some zooms there are still too many state labels. Europe, z6:

![screen shot 2015-10-28 at 2 09 16 pm](https://cloud.githubusercontent.com/assets/1212178/10803044/84549816-7d7d-11e5-862e-9c48535d4196.png)

Europe, z7:
![screen shot 2015-10-28 at 2 09 45 pm](https://cloud.githubusercontent.com/assets/1212178/10803108/d65a155a-7d7d-11e5-80a7-6eae71303663.png)


And sometimes maybe we could skip them if the names are really long, or use some kind of "short name" field in natural earth?
Ethiopia, z6:
![screen shot 2015-10-28 at 2 07 50 pm](https://cloud.githubusercontent.com/assets/1212178/10803030/6bf3fc1c-7d7d-11e5-9f08-fdd987663f81.png)

**Comment by clhenrick** [comment]
I played around with this some and it seems like using the `scalerank` value alone doesn't help much for Europe at lower zooms. Changing  `[scalerank <= x ]` from 4 -10 doesn't seem to change anything at zooms 5-7. This is because most of the state / province polygons for larger European countries have a `scalerank` value of 3. Thus going lower than 3 removes the labels completely. Conversely, most of the smaller European countries have larger values for `scalerank` so they won't display at all until 4+.

Regarding the longer labels such as the one in Ethiopia; I didn't see a "short-name" column in the `ne_10m_admin_1_states_provinces_scale_rank` table which could be used for longer admin1 names either. We could also do some filtering on the `featureclass` attribute to ignore admin1 areas such as minor islands and aggregations. But unsure if that's a good idea or not? Or we could filter by string length to not display those labels that are very long.

However, reducing the `text-size` and lightening the `text-fill` of the `admin1-labels` layer seems to help the labels from over-powering the map style.

Here are some screenshots from zooms 5 - 7 (previously admin1 labels weren't displaying in Europe at z5):

![screen shot 2015-11-03 at 12 08 43 pm](https://cloud.githubusercontent.com/assets/161748/10915380/913a303a-8224-11e5-8a8c-ce446b0a6516.png)

![screen shot 2015-11-03 at 12 09 42 pm](https://cloud.githubusercontent.com/assets/161748/10915382/932a619e-8224-11e5-9c0a-8804a0a47a7d.png)

![screen shot 2015-11-03 at 12 12 55 pm](https://cloud.githubusercontent.com/assets/161748/10915386/9555640a-8224-11e5-8972-cebf64755c60.png)

**Comment by almccon** [comment]
These are looking pretty good. I made them a little bit smaller and more gray. Calling this one finished!
