### ISSUE TITLE
Park boundaries should trump landcover data at higher zooms

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#20]
Looks like with the new terrain-classic park boundaries aren't being rendered and that the landcover data is displaying at high zoom levels.
![screen shot 2015-08-27 at 12 08 31 pm](https://cloud.githubusercontent.com/assets/161748/9525900/6a04f072-4cb4-11e5-9dc7-18753957dddc.png)

There must be a rule in cascadenik for the og terrain tiles that decides when to swap landcover data for park boundaries as the polygon layer to composite onto the hillshades.
![screen shot 2015-08-27 at 12 08 24 pm](https://cloud.githubusercontent.com/assets/161748/9525903/6de60c8a-4cb4-11e5-83c4-ccec15e263f8.png)

Looks like at zoom 10 park boundaries start showing up, possibly on top of dimmed landcover data? Then at zoom > 10 park boundaries are more definitive.

**Comment by clhenrick** [comment]
On further inspection it seems that park boundaries are being drawn but the landcover styling is over powering them.

**Comment by clhenrick** [comment]
We might want to dissolve the osm green areas at low zoom levels as overlapping polygons create darker areas due to the transparency. Or could we solve this with a `polygon-comp-op`?

![screen shot 2015-09-02 at 5 45 13 pm](https://cloud.githubusercontent.com/assets/161748/9645578/98b42560-519a-11e5-83ef-27f961f9db3f.png)
![screen shot 2015-09-02 at 5 45 03 pm](https://cloud.githubusercontent.com/assets/161748/9645579/98b563bc-519a-11e5-8e5c-61931dfffb84.png)

**Comment by clhenrick** [comment]
"Dissolving" the polygons for higher zooms seems to solve the problem of overlapping park boundaries but I'm not sure if this would work for a planet file as it merges all the parks into one polygon. Perhaps grouping by type would be a better method?

![screen shot 2015-09-02 at 8 05 41 pm](https://cloud.githubusercontent.com/assets/161748/9647726/0a85ee36-51ae-11e5-8d5d-96122da46124.png)


```sql
CREATE TABLE osm_green_areas_z13_dissolved AS (
SELECT ST_Multi(ST_BuildArea(ST_Buffer(ST_collect(geometry), 0))) as geometry, 
SUM(area) as area 
FROM osm_green_areas_z13
);

ALTER TABLE osm_green_areas_z13_dissolved ADD COLUMN type character varying;
UPDATE osm_green_areas_z13_dissolved SET type = 'park';
```

Any thoughts @almccon @seth?

**Comment by clhenrick** [comment]
I'm noticing that in the OG terrain the style for parks with larger areas may have been made more transparent and had their borders blurred while smaller parks were given a more opaque fill and solid borders. 

Notice Tilden Golf Course to the lower left and the area around the reservoir to the middle top:
![screen shot 2015-09-07 at 12 51 23 pm](https://cloud.githubusercontent.com/assets/161748/9720803/fe6b315a-555f-11e5-8d85-85909006375f.png)

**Comment by clhenrick** [comment]
Proposed solution:
- forget about dissolving park areas for higher zooms
- instead ditch the `polygon-opacity` and use `polygon-comp-op: src;`

This seems to dissolve the overlapping park boundaries as well as provide a blending with the terrain underneath.

Here is a screen shot from TileMill showing the dissolved overlapping boundaries:

![screen shot 2015-09-07 at 2 11 00 pm](https://cloud.githubusercontent.com/assets/161748/9721587/32872538-556b-11e5-90d9-547ff8928b0a.png)

And here is a screen shot from Tessera running with the very pixellated hillshade underneath:

![screen shot 2015-09-07 at 2 11 11 pm](https://cloud.githubusercontent.com/assets/161748/9721590/4d1bd880-556b-11e5-9375-b963fb27c1d3.png)

The only to-do will likely be tweaking the `osm-green-areas` color to make it a little less obtrusive when the final tiles are rendered.

**Comment by almccon** [comment]
Nice. Works for me. I agree we might want a color tweak, but the composite effect looks great.

**Comment by clhenrick** [comment]
:+1:
