### ISSUE TITLE
Street casings for roads at higher zoom levels?

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#21]
Right now at zoom 18 (max zoom level) smaller roads (non-highways) are being displayed with casings, is this something we want to change for higher zoom levels with the updated terrain tiles?
![screen shot 2015-08-27 at 12 21 46 pm](https://cloud.githubusercontent.com/assets/161748/9526302/8d2a4a82-4cb6-11e5-80a5-c2eeb4581691.png)

![screen shot 2015-08-27 at 12 21 40 pm](https://cloud.githubusercontent.com/assets/161748/9526308/927a0c2a-4cb6-11e5-9c4b-a1430d638225.png)

**Comment by almccon** [comment]
I'm 100% sure that's a holdover from the Toner style. Currently Toner switched from black roads to white w/ casing at the z17 to 18 transition. I suggest removing the casings for terrain

**Comment by clhenrick** [comment]
Okay, sounds good.

**Comment by clhenrick** [comment]
@almccon do we want to drop casings for most road styles and zooms? From a first glance it looks like only freeways that are bridges and overpasses have them at zoom < 16.

**Comment by almccon** [comment]
Yeah, probably. Unless you think it looks gross, then don't. :)

**Comment by clhenrick** [comment]
Taking a closer look it seems like the casings help the roads stand out over the terrain at higher zooms so I decided on keeping them. Also fixed the issue with the minor roads changing their inline fill color at zoom 18.
![screen shot 2015-08-28 at 4 58 02 pm](https://cloud.githubusercontent.com/assets/161748/9556912/00fc076c-4da6-11e5-84a5-9d7d150a91e2.png)
