### ISSUE TITLE
Check for improved landcover resolution

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#22]
Currently we're using the 5'x5' MODIS landcover from here: http://glcf.umd.edu/data/lc/ That's a raster of 1776 rows x 4320 columns.

That source also has a link to "native resolution" tiles, but it doesn't say what resolution those tiles are. Are they better resolution? We should find out.

**Comment by almccon** [comment]
Also, when we've settled on the final source, we should add the appropriate citation. From that page, here's how we should cite:


>
How to Cite This Data Set
Data set development attribution:
Channan, S., K. Collins, and W. R. Emanuel. 2014. Global mosaics of the standard MODIS land cover type data. University of Maryland and the Pacific Northwest National Laboratory, College Park, Maryland, USA.

>MODIS standard data product attribution:
Friedl, M.A., D. Sulla-Menashe, B. Tan, A. Schneider, N. Ramankutty, A. Sibley and X. Huang (2010), MODIS Collection 5 global land cover: Algorithm refinements and characterization of new datasets, 2001-2012, Collection 5.1 IGBP Land Cover, Boston University, Boston, MA, USA.

>Intellectual Property Rights
University of Maryland, Department of Geography and NASA; use is free to all if acknowledgement is made. UMD and NASA hold ultimate copyright.

**Comment by clhenrick** [comment]
Okay that makes sense. Is the landcover data used for the original terrain tiles for the U.S. better resolution? Should we stick to that for the U.S.?

**Comment by almccon** [comment]
I looked at that a bit in #3... because at first I thought our North America data was higher resolution... but I've subsequently found better resolution global data, so we'll just use that. Plus, the landuse classes in the original North America raster are different from the classes in the global MODIS data. So the landcover areas wouldn't exactly line up with each other when you switch from one area to another. So that's another reason to use a single source for landcover.

**Comment by almccon** [comment]
Oh wait, or did I download it from here? http://landcover.usgs.gov/global_climatology.php I'm not sure anymore.

**Comment by clhenrick** [comment]
@almccon I'm closing this for now as it seems we are settled on using the USGS 0.5 km MODIS data.
