### ISSUE TITLE
Improve styling of new global landcover data

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#23]
reference #12

**Comment by clhenrick** [comment]
@almccon  I pulled out the RGB values from the VRT file for the previously used landcover data, matched them up with the legend you posted in #12 and this is what I got:

```
Urban and Built-Up Land = r: 0 g: 0 b: 0
Dryland Cropland and Pasture = r: 239 g: 239 b: 239
Irrigated Cropland and Pasture = r: 222 g: 224 b: 190
Mixed Dryland/Irrigated Cropland and Pasture = r: 213 g: 224 b: 164
Cropland/Grassland Mosaic = r: 0 g: 0 b: 0
Cropland/Woodland Mosaic = r: 213 g: 224 b: 164
Grassland = r: 9 g: 174 b: 132
Shrubland = r: 222 g: 224 b: 190
Mixed Shrubland/Grassland = r: 221 g: 224 b: 206
Savanna = r: 221 g: 224 b: 206
Deciduous Broadleaf Forest = r: 222 g: 224 b: 190
Deciduous Needleleaf Forest = r: 43 g: 174 b: 103
Evergreen Broadleaf Forest = r: 43 g: 174 b: 103
Evergreen Needleleaf Forest = r: 43 g: 174 b: 103
Mixed Forest = r: 43 g: 174 b: 103
Water Bodies = r: 43 g: 174 b: 103
Herbaceous Wetland = r: 222 g: 224 b: 190
Wooded Wetland = r: 0 g: 0 b: 0
Barren or Sparsely Vegetated = r: 0 g: 0 b: 0
Herbaceous Tundra = r: 239 g: 243 b: 217
Wooded Tundra = r: 0 g: 0 b: 0
Mixed Tundra = r: 43 g: 174 b: 103
Bare Ground Tundra = r: 222 g: 224 b: 190
Snow or Ice = r: 0 g: 0 b: 0
```

Looks like some of these categories have `0,0,0` which makes sense because they're mostly absent in the U.S. I'd imagine? Thinking we may have to come up with new values for global coverage.

**Comment by clhenrick** [comment]
This color chart is from a [Tom Harrison blog post](http://www.shadedrelief.com/shelton/c.html#fig_11) and might be a good starting point:

![pasted image at 2015_08_31 03_54 pm](https://cloud.githubusercontent.com/assets/161748/9589136/4e831b1e-4ffa-11e5-9836-059b303148d7.png)

Pulled out the color values from the image and they are here:
![screen shot 2015-08-31 at 4 07 17 pm](https://cloud.githubusercontent.com/assets/161748/9589177/8cc41d10-4ffa-11e5-8cb3-a23ba0c94c48.png)

**Comment by clhenrick** [comment]
Here are some screen shots after applying the above color palette:
![screen shot 2015-09-03 at 12 48 53 pm](https://cloud.githubusercontent.com/assets/161748/9664872/7ebaacc4-523a-11e5-8c55-0130d5cd5168.png)
![screen shot 2015-09-03 at 12 49 44 pm](https://cloud.githubusercontent.com/assets/161748/9664874/81b7fbac-523a-11e5-8884-7de65a4f5fb0.png)
![screen shot 2015-09-03 at 12 50 01 pm](https://cloud.githubusercontent.com/assets/161748/9664877/86023966-523a-11e5-9449-02f714838346.png)

**Comment by clhenrick** [comment]
Here is the new landcover style viewed while running Tessera at zoom 9:

![screen shot 2015-09-07 at 2 23 50 pm](https://cloud.githubusercontent.com/assets/161748/9721636/c81566fe-556c-11e5-9fc7-6dd9495a4277.png)

Vs. OG Terrain style:

![screen shot 2015-09-07 at 2 23 57 pm](https://cloud.githubusercontent.com/assets/161748/9721639/dde989b0-556c-11e5-8755-8c8af2328959.png)

**Thoughts:**  
- Something about the bright yellowish color next to the deep green in the sierra nevada doesn't sit well with me. According to the new lancover data these are grassland areas.
- Perhaps changing to lighter green would provide for a better transition?
- Or did the OG Terrain tiles include park areas at lower zoom levels to get that much of a deep green coverage? Is that something we'd like to replicate?

**Comment by almccon** [comment]
Hmm. I don't think that OG Terrain is doing anything with park areas at that zoom. I think it's just a difference in classification between the two landcover sources.

I think we should nudge the Tom Patterson colors in the direction of the OG palette, even if it reduces the amount of variation. Especially the yellows of the grassland and the blue-green color of the evergreen forests should converge on the overall olive tones of OG.

**Comment by clhenrick** [comment]
@almccon sounds good, I'll give it a shot.

**Comment by clhenrick** [comment]
Altered the palette towards being a little more olive similar to the OG Terrain. Here's the shot of the Bay Area to the Sierra Nevada:
![screen shot 2015-09-09 at 11 57 42 am](https://cloud.githubusercontent.com/assets/161748/9767018/0b706c72-56ea-11e5-8abc-3571929dc0dd.png)

North America:
![screen shot 2015-09-09 at 11 57 22 am](https://cloud.githubusercontent.com/assets/161748/9767054/3a2c1552-56ea-11e5-8b5d-2ae69f74eb78.png)

North Africa / Southern Europe:
![screen shot 2015-09-09 at 11 56 18 am](https://cloud.githubusercontent.com/assets/161748/9767062/4942a90c-56ea-11e5-8dcc-0718ee709bbe.png)

I would've liked to grab these screen shots while running Tessera but it seems to be busted for me currently. Looks like something to do with the terrain-class.mss file being in a sub-directory?

**Comment by clhenrick** [comment]
Here's a screenshot while running Tessera:
![screen shot 2015-09-09 at 1 05 51 pm](https://cloud.githubusercontent.com/assets/161748/9768740/8de33f28-56f3-11e5-897a-a9315fc4f266.png)

**Comment by clhenrick** [comment]
- make forests less blue so they don't clash with park color
- brown out grasslands color (see transition to southern Sahara)

**Comment by clhenrick** [comment]
@almccon modified: evergreen forests > less blue; grasslands > more brown:

![screen shot 2015-09-14 at 7 21 27 pm](https://cloud.githubusercontent.com/assets/161748/9864277/ec39bc16-5b15-11e5-8633-4c933107224d.png)
![screen shot 2015-09-14 at 7 21 57 pm](https://cloud.githubusercontent.com/assets/161748/9864279/ef48ae62-5b15-11e5-9628-e6d5ef5aabf4.png)

**Comment by clhenrick** [comment]
seems like it clashes less with parks at higher zooms now as well:
![screen shot 2015-09-14 at 7 24 21 pm](https://cloud.githubusercontent.com/assets/161748/9864314/4820a882-5b16-11e5-92c0-dcdbdc7bd8fc.png)

**Comment by almccon** [comment]
Yeah, looks really good. It might be a little too yellow overall... like I expect to see a little bit more green adjacent to the rainforests in Africa and Brazil. But as far as I'm concerned this is good enough to launch, so I'm happy to leave any further color tweaks as a nice-to-have.

**Comment by clhenrick** [comment]
hmmm, yeah I agree about it looking too yellow, I'll try tweaking the grasslands color once more.

**Comment by clhenrick** [comment]
Attempted tweaking the grasslands color a bit, but think the issue may also have to do with what areas the data classifies as grassland. When comparing the current style of the new data with the OG style and data it's very noticeable that areas were classified differently. The new data seems to apply the grassland classification to a much broader area then the old data.
![screen shot 2015-09-15 at 10 07 12 am](https://cloud.githubusercontent.com/assets/161748/9879626/3b0d1ba0-5b96-11e5-8e9b-27572838f174.png)
![screen shot 2015-09-15 at 9 41 37 am](https://cloud.githubusercontent.com/assets/161748/9879640/450cdd48-5b96-11e5-8227-95ebd8c5712f.png)

If you don't approve of the current iteration I'll revert to the previous one from above.

**Comment by almccon** [comment]
Thwarted by those grasslands again! I think that was my original problem with this data. Let's revert.

**Comment by clhenrick** [comment]
reverted!

**Comment by almccon** [comment]
I couldn't resist one more tweak to bring in even more of the olive color from the OG style, plus some more greenish in the woody savanna adjacent to the jungles in Africa.

![screen shot 2015-09-18 at 2 28 19 pm](https://cloud.githubusercontent.com/assets/1212178/9971587/df0efcf0-5e11-11e5-9c8f-a32174c3cf6b.png)

**Comment by clhenrick** [comment]
I like it!

On Friday, September 18, 2015, Alan McConchie <notifications@github.com>
wrote:

> I couldn't resist one more tweak to bring in even more of the olive color
> from the OG style, plus some more greenish in the woody savanna adjacent to
> the jungles in Africa.
>
> [image: screen shot 2015-09-18 at 2 28 19 pm]
> <https://cloud.githubusercontent.com/assets/1212178/9971587/df0efcf0-5e11-11e5-9c8f-a32174c3cf6b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/terrain-classic/issues/23#issuecomment-141573972>
> .
>


-- 

-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells
