### ISSUE TITLE
Labeling typography improvements

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#27]
We could definitely improve the typography by doing some simple things such as:

- [x] spacing out the kerning via the `text-character-spacing` property.
- [x] using italic fonts in labels such as water bodies, natural features, parks.
- [x] varying the font-size of place labels based on something like `scale-rank` from natural earth
- [ ] creating angled labels along a path for features such as mountain ranges and valleys

@almccon & @mojodna does PT Sans Narrow have an italic font? I don't see it when inspecting via font-book. We might want to choose a font that has more options, at least one that has italic and bold-italic.

**Comment by almccon** [comment]
Looks like it has an italic, but not a narrow italic: http://www.fontsquirrel.com/fonts/pt-sans

I've got no problem adding the non-narrow italic and bold italic wherever you see fit! Go ahead and download the ttf from that link and add to the repo.

**Comment by clhenrick** [comment]
:+1:

**Comment by clhenrick** [comment]
- [ ] Use bold fonts for admin0 & admin1 labels
- [ ] Tweak city dots & labels (try styling as highway shields to avoid having dots without a label)

**Comment by almccon** [comment]
Labels are looking good to me now. We can reopen individual issues as we find new things.
