### ISSUE TITLE
Makefile updates

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#28]
## Processes to add to the Makefile include:

- [x] importing the Aries place data into PostGIS.
- [x] ~~process Aries from GeoJSON to SHP & reproject (only needed if the data isn't accessible via PostGIS)~~
- [x] compile sub-directory of `.mss` files into single `.mml` files
- [x] generate highway shields table in Postgres using `sql/highway_shields.sql`
- [x] add ne_10m_admin_1_labels to PostGIS using `sql/admin1_labels.sql` 
  (also requires dl'ing & extracting [ne_10m_admin_1_states_provinces](http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_scale_rank.zip))*

\* I imported the `ne_10m_admin_1_states_provinces` data into PostGIS by doing the following:

```
$ shp2pgsql -s 4326 -I -g geometry \ 
~/data/natural_earth_vector/ne_10m_admin_1_states_provinces_scale_rank.shp \
ne_10m_admin_1_states_provinces terrain_tokyo | psql -d terrain_tokyo
```

**Comment by almccon** [comment]
So we're adding ne_10m_admin_1_labels to the database and not the others because we do the generalization for #16 in PostGIS?

**Comment by clhenrick** [comment]
@almccon yes that's correct.

**Comment by almccon** [comment]
I'm just giving up on the mss/ folder. We'll just keep everything in the few monster .mss files for now.
