### ISSUE TITLE
remove the phased-in buildings

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#29]
It's a nice touch in Toner, but it would be nice to make this map look less like Toner

![screen shot 2015-09-18 at 5 57 59 pm](https://cloud.githubusercontent.com/assets/1212178/9973829/e7f61bc4-5e2e-11e5-9077-c24f3fa305e6.png)

`http://localhost:8080/background/#15/37.7775/-122.4386`

**Comment by clhenrick** [comment]
@almccon by "phased in buildings" do you mean larger buildings showing up at medium-low zooms and then more buildings showing up at higher zooms?

**Comment by almccon** [comment]
Correct. I was just thinking that Terrain should do something different. Or at least we should try removing the phasing-in, and see how it looks.

**Comment by clhenrick** [comment]
Right now turning off the `buildings-med` layer for zoom 13 doesn't really seem to have much of an effect, at least in SF. However I really notice a jump between zoom 15 and 16 where all of the smaller buildings for houses show up. 

I'm thinking that it may be worth revisiting this issue once we have the higher resolution hillshade rendered. Then we can determine at what zoom level the hillshade becomes un-noticeable and that might inform how we choose to render buildings.

**Comment by almccon** [comment]
Good point. Let's close for now and worry about it later. It's pretty low priority.
