### ISSUE TITLE
Remove non interstate/US highway shields from small roads at z11

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#31]
When state highways aren't motorways, we should avoid giving them shields until you zoom in more. It's especially acute at zoom 11 where they are still drawn with a very thin line:

http://localhost:8080/#11/33.6138/-116.6968

![screen shot 2015-09-18 at 6 31 21 pm](https://cloud.githubusercontent.com/assets/1212178/9973984/b57b67d0-5e33-11e5-991d-8518ffd31a4f.png)

**Comment by clhenrick** [comment]
Good catch! Hadn't noticed that before.

On Friday, September 18, 2015, Alan McConchie <notifications@github.com>
wrote:

> When state highways aren't motorways, we should avoid giving them shields
> until you zoom in more. It's especially acute at zoom 11 where they are
> still drawn with a very thin line:
>
> http://localhost:8080/#11
> <https://github.com/stamen/terrain-classic/issues/11>/33.6138/-116.6968
>
> [image: screen shot 2015-09-18 at 6 31 21 pm]
> <https://cloud.githubusercontent.com/assets/1212178/9973984/b57b67d0-5e33-11e5-991d-8518ffd31a4f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/terrain-classic/issues/31>.
>


-- 

-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by clhenrick** [comment]
think that ^ should do it.

**Comment by almccon** [comment]
Looks good!
