### ISSUE TITLE
Duplicated city labels

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#35]
http://localhost:8080/flat/#9/17.8598/-98.4595

These cities fall right on a tile boundary, so they get labeled twice:

![screen shot 2015-09-21 at 2 39 00 pm](https://cloud.githubusercontent.com/assets/1212178/10006100/d19dec88-606f-11e5-8a90-a9f002b5d8d7.png)

**Comment by almccon** [comment]
Actually, it's happening elsewhere. Here's one that's not on a tile boundary:

![screen shot 2015-10-02 at 6 01 56 pm](https://cloud.githubusercontent.com/assets/1212178/10260704/9a8c1610-6930-11e5-9394-9aaaa78ae460.png)

I think instead I need to increase `shield-min-distance`, perhaps? Actually, in 6d0fe2a54ff470e9ecd326398ed5c0f7303d97de I have `shield-min-distance` in there twice. Hmm.

**Comment by clhenrick** [comment]
Strange, I'll take a look later and see if I can replicate it.

On Friday, October 2, 2015, Alan McConchie <notifications@github.com> wrote:

> Actually, it's happening elsewhere. Here's one that's not on a tile
> boundary:
>
> [image: screen shot 2015-10-02 at 6 01 56 pm]
> <https://cloud.githubusercontent.com/assets/1212178/10260704/9a8c1610-6930-11e5-9394-9aaaa78ae460.png>
>
> I think instead I need to increase shield-min-distance, perhaps?
> Actually, in 6d0fe2a
> <https://github.com/stamen/terrain-classic/commit/6d0fe2a54ff470e9ecd326398ed5c0f7303d97de>
> I have shield-min-distance in there twice. Hmm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/terrain-classic/issues/35#issuecomment-145190814>
> .
>


-- 

-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by clhenrick** [comment]
@almccon think this is resolved via cecbc0b could you verify on your end?
