### ISSUE TITLE
label collisions at lower zooms

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#36]
z9: ![screen shot 2015-10-06 at 1 30 25 pm](https://cloud.githubusercontent.com/assets/1212178/10321612/7e5dea3a-6c2e-11e5-837e-cd0250538f27.png)

z9: ![screen shot 2015-10-06 at 1 31 12 pm](https://cloud.githubusercontent.com/assets/1212178/10321616/895edd04-6c2e-11e5-9128-68ae36c923ad.png)

z8: 
![screen shot 2015-10-06 at 1 32 46 pm](https://cloud.githubusercontent.com/assets/1212178/10321671/c3479d58-6c2e-11e5-8fc3-6ee0af6598ff.png)

z7:
![screen shot 2015-10-06 at 1 33 16 pm](https://cloud.githubusercontent.com/assets/1212178/10321683/d55c6136-6c2e-11e5-81e6-79ebebee3549.png)

I'm only seeing this at <= zoom 9, and I'm only seeing it related to city labels, so possibly fixing #35 will fix it.

**Comment by clhenrick** [comment]
@almccon think this is resolved via cecbc0b could you verify on your end?
