### ISSUE TITLE
Enable highway shields in other countries 

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#37]
I'm not sure why the default shield isn't showing up, but when I use extracts outside the US I don't get any highway shields, and when I use extracts of other US states, I don't get any of their state shields.

![screen shot 2015-10-06 at 5 26 39 pm](https://cloud.githubusercontent.com/assets/1212178/10326539/592b1f44-6c51-11e5-8b18-8f3c4660a070.png)
![screen shot 2015-10-06 at 5 21 46 pm](https://cloud.githubusercontent.com/assets/1212178/10326540/593f17ec-6c51-11e5-86d8-97ae3a768a7d.png)
![screen shot 2015-10-06 at 5 39 15 pm](https://cloud.githubusercontent.com/assets/1212178/10326541/5cc56b5a-6c51-11e5-9beb-b963368c4f88.png)

**Comment by clhenrick** [comment]
Looking into the highway_shields table in Postgres for a New York state extract and I only see shields for interstates. Perhaps the SQL is not capturing the "ref" tag for other states? Looking into it further now.

**Comment by clhenrick** [comment]
So it looks as if the shields are showing up in other U.S. states & countries now. I checked Tokyo, New York state, and Mexico City. 

![screen shot 2015-10-22 at 3 35 24 pm](https://cloud.githubusercontent.com/assets/161748/10676562/2ccd648a-78d5-11e5-822d-c970f2f98bb3.png)

![screen shot 2015-10-22 at 3 39 16 pm](https://cloud.githubusercontent.com/assets/161748/10676568/359ff064-78d5-11e5-9792-92f057a1c013.png)

![screen shot 2015-10-22 at 3 53 14 pm](https://cloud.githubusercontent.com/assets/161748/10676571/3a3752de-78d5-11e5-8a45-a9939afb2833.png)

One thing I've noticed is that we may want different widths for the default highway shield. Shields for Mexico City tend to overflow while those for Vancouver seem too large. Or perhaps for longer `ref` strings we can shrink the text size slightly.

![screen shot 2015-10-22 at 3 56 43 pm](https://cloud.githubusercontent.com/assets/161748/10676714/12d8b772-78d6-11e5-9275-26f025401cee.png)

![screen shot 2015-10-22 at 4 03 19 pm](https://cloud.githubusercontent.com/assets/161748/10676777/83c60552-78d6-11e5-84a5-c82e4c8b04a0.png)

**Comment by almccon** [comment]
I just did a bunch of work creating multiple-sized highway shields for another map we're working on, mostly borrowing from openstreetmap-carto (see for example [this elaborate script](https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/generate_shields.py) that produces a ton of similar shields of various sizes. Those shields get saved into a folder like this: https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shields

I can try porting some of that code over to this repo, or if you felt like diving into it you could try borrowing some code from openstreetmap-carto to accomplish the same effect.

**Comment by clhenrick** [comment]
that looks interesting @almccon, I'm open to testing them out. Do you happen to know which `.mss` file contains the carto code for assigning the shields?

**Comment by clhenrick** [comment]
ah nevermind, found it: https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss#L2581

**Comment by clhenrick** [comment]
Looks like 
```
select distinct char_length(ref) from highway_shields order by char_length;
``` 
typically returns 1 as the lowest and 7 being the largest value. However in Tokyo I noticed a 23 because someone edited `ref` as being "Road joining 408 and 53", so we'd also have to exclude values from `ref` > 7.

**Comment by clhenrick** [comment]
Think I've got it working so that we only render default tiles for non US interstates and that the default shield size changes based on the amount of text, ie: `char_length(ref)`.

Here's Victoria, BC
![screen shot 2015-10-23 at 11 26 31 pm](https://cloud.githubusercontent.com/assets/161748/10708651/c1fc1304-79dd-11e5-82af-02c87a8e859b.png)

And here's Seattle
![screen shot 2015-10-23 at 11 30 35 pm](https://cloud.githubusercontent.com/assets/161748/10708659/16cccfe0-79de-11e5-81b8-fcd23bbad541.png)

Still need to test over-seas but think it's looking good so far.

**Comment by clhenrick** [comment]
closing for now.
