### ISSUE TITLE
Fix gaps between adjacent water polygons

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#40]
Noticed this while looking at the Hudson River in an New York extract. I'm guessing this is why there was a stroke applied to water polygons? I believe we previously removed at very low zooms but perhaps enabling them at higher zooms will fix this. That or a union in PostGIS?

![screen shot 2015-10-22 at 3 39 01 pm](https://cloud.githubusercontent.com/assets/161748/10678701/075281f6-78e2-11e5-9d82-9c09e7325afc.png)

**Comment by almccon** [comment]
Looks like an error in OSM:
![screen shot 2015-10-22 at 2 36 50 pm](https://cloud.githubusercontent.com/assets/1212178/10678954/62953864-78ca-11e5-869f-70ed076f7d09.png)

Not sure if any stroke would be thick enough to fix it for good.

**Comment by almccon** [comment]
I'm going to try to fix it in OSM. When we deploy this for real, hopefully the data will still be fixed by that time.

**Comment by clhenrick** [comment]
Okay, good catch!

**Comment by almccon** [comment]
In case anyone cares: http://www.openstreetmap.org/changeset/34810760

**Comment by clhenrick** [comment]
:+1:

**Comment by clhenrick** [comment]
@almccon that's great actually because I'm often making maps of NYC with that data and have been scratching my head why it gets cut off about halfway up!
:+1:
