### ISSUE TITLE
Draw OSM glaciers

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#43]
Here's Mt. Baker at z9, showing only the landcover data. Nice white-topped mountain:

![screen shot 2015-10-26 at 12 47 26 pm](https://cloud.githubusercontent.com/assets/1212178/10740502/d88cec20-7bdf-11e5-9fa3-393dc6b07e97.png)

Then at z10 we start drawing national forests, and this ice-covered peak looks solid green: 
![screen shot 2015-10-26 at 12 47 33 pm](https://cloud.githubusercontent.com/assets/1212178/10740526/f6323492-7bdf-11e5-9c81-2b27612e5c30.png)

OSM has good glacier features... we should draw them:
![screen shot 2015-10-26 at 12 49 44 pm](https://cloud.githubusercontent.com/assets/1212178/10740553/1a78e6fc-7be0-11e5-9bad-084e8a8be0e8.png)

...but I think I will have to pull out yet another OSM feature in imposm.

**Comment by almccon** [comment]
But then, why stop there? Perhaps part of the solution to #41 is to bring in even more `landuse`, `landcover`, and `natural` features from OSM, and more-or-less match their colors to the MODIS landcover raster. Going to give it a try, wish me luck.

**Comment by mojodna** [comment]
:four_leaf_clover:

**Comment by almccon** [comment]
Glaciers are looking good:

Mt. Baker:
![screen shot 2015-10-26 at 5 39 44 pm](https://cloud.githubusercontent.com/assets/1212178/10746479/b8ca5304-7c08-11e5-8aa3-eb6c2d846e1e.png)

Mt. Adams:
![screen shot 2015-10-26 at 5 40 34 pm](https://cloud.githubusercontent.com/assets/1212178/10746485/be8fc5bc-7c08-11e5-9400-9f364879cec9.png)

**Comment by almccon** [comment]
I also brought in a bunch of other landcover features, which look great:
![screen shot 2015-10-26 at 5 44 24 pm](https://cloud.githubusercontent.com/assets/1212178/10746550/508f06da-7c09-11e5-833b-98c9cb1175ad.png)

**Comment by clhenrick** [comment]
Awesome!
