### ISSUE TITLE
halo at low zooms: blur?

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#5]
Looks like the original terrain does a blur, which helps:

![screen shot 2015-06-19 at 6 40 25 pm](https://cloud.githubusercontent.com/assets/1212178/8265569/be92a946-16b2-11e5-8ba9-6b00a63fe9ec.png)

**Comment by almccon** [comment]
This is true for some labels all the way up to zoom 11:
![screen shot 2015-06-19 at 6 41 42 pm](https://cloud.githubusercontent.com/assets/1212178/8265570/df377fd2-16b2-11e5-8ba7-641b450ed019.png)
Notice that San Francisco has a blur halo, but the parks just have a colored halo

**Comment by clhenrick** [comment]
Applying the following helps but makes the labels stand out too much when they are over water or green areas.

```
  text-halo-radius: 2;
  text-halo-fill: fadeout(rgba(255,255,255, 0.7), 30%);
```

![screen shot 2015-08-28 at 6 25 11 pm](https://cloud.githubusercontent.com/assets/161748/9558340/5bc67c7a-4db2-11e5-8f38-f8839a5d47f1.png)

**Comment by clhenrick** [comment]
Haven't had much luck attempting to implement the blur halo effect from the og tiles. None of the `comp-op` effects seem to grab the color under the text halo. The best I found so far seems to be `text-halo-comp-op: overlay;` but it's fairly subtle.
![screen shot 2015-09-01 at 11 30 34 am](https://cloud.githubusercontent.com/assets/161748/9608536/ea9908fe-509c-11e5-97d5-8d1b7ac87ed2.png)

**Comment by clhenrick** [comment]
Marking as resolved for now
![screen shot 2015-09-01 at 3 46 11 pm](https://cloud.githubusercontent.com/assets/161748/9614592/a9d04ad4-50c0-11e5-9588-bfdfedb1f621.png)
