### ISSUE TITLE
Move water features & buildings from background.yml to a new features.yml

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#56]
To mask out DEM artifacts in water:

![pasted image at 2016_06_30 05_42 pm](https://cloud.githubusercontent.com/assets/161748/16534920/47b63bf2-3f98-11e6-8a0e-b3047db3a4e8.png)

and avoid blending buildings into landcover:

![pasted image at 2016_06_30 04_53 pm](https://cloud.githubusercontent.com/assets/161748/16534932/5b54c9a8-3f98-11e6-90a8-d6c158d7677f.png)

**Comment by mojodna** [comment]
Fixed in #57
