### ISSUE TITLE
Labels are being lost in areas with lots of terrain

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#59]
For example in Switzerland @ `#7/46.294/11.920`:

![screen shot 2016-07-03 at 11 10 19 am](https://cloud.githubusercontent.com/assets/161748/16546957/6318f136-4110-11e6-8c54-9e6bc4d5e7cd.png)

Simple fix would be to bump up halos on all labels, though it might look odd in areas with little to no terrain. Thoughts @almccon ?

**Comment by almccon** [comment]
I think slightly bigger halos will be fine everywhere. The Alps are also reminding me that we might want to town down the hillshade compositing a little bit. Does it feel like the highlights are too white and the shadows too black?

**Comment by clhenrick** [comment]
Agreed. Yes I think toning it down a bit would be helpful as well.

**Comment by almccon** [comment]
There are some halo radii defined here: https://github.com/stamen/terrain-classic/blob/feea30ed912f0a2e6f7de492df6a242e8f56899f/labels.mss#L29-L32 but I'm not sure which labels actually use them. 

If those cities are Aries labels, then here is the jump between z9 and z10 you're seeing: https://github.com/stamen/terrain-classic/blob/feea30ed912f0a2e6f7de492df6a242e8f56899f/labels.mss#L681-L695

Maybe the lower zoom halos just need to be beefed up.

**Comment by clhenrick** [comment]
After 1265f7f labels are looking like so:
![screen shot 2016-07-05 at 2 31 39 pm](https://cloud.githubusercontent.com/assets/161748/16600687/3ff2c070-42bd-11e6-92a6-02feef0d6b38.png)
![screen shot 2016-07-05 at 2 31 22 pm](https://cloud.githubusercontent.com/assets/161748/16600686/3feec79a-42bd-11e6-9c86-05c435ac6c94.png)

**Comment by almccon** [comment]
Love it!
