### ISSUE TITLE
Hillshade getting chopped off at zoom 7

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#60]
At zoom 6 you can see the extent of the Swiss Alps:

![screen shot 2016-07-03 at 11 24 12 am](https://cloud.githubusercontent.com/assets/161748/16546963/bf7de0b2-4110-11e6-8cf5-a38cb701fc20.png)

However, at zoom 7 they appear to be getting chopped off at a tile boundary:
![screen shot 2016-07-03 at 11 24 00 am](https://cloud.githubusercontent.com/assets/161748/16546969/e17ee9fe-4110-11e6-89c5-86d581b3e7ed.png)

Not sure if this has to do with Tessera or the hillshade rendering process. cc @mojodna

**Comment by clhenrick** [comment]
exact tile in this case appears to be `7/66/45.png`

**Comment by mojodna** [comment]
Looks like a request timeout or something--production is fine:

![http://tmp.openterrain.org.s3.amazonaws.com/terrain/7/66/45.png](http://tmp.openterrain.org.s3.amazonaws.com/terrain/7/66/45.png)

![http://tmp.openterrain.org.s3.amazonaws.com/terrain/7/66/46.png](http://tmp.openterrain.org.s3.amazonaws.com/terrain/7/66/46.png)
