### ISSUE TITLE
Language labeling inconsistencies in China (and perhaps beyond)

### ISSUE THREAD

**Issue by geoglrb** [stamen/terrain-classic#75]
Hi, perhaps an OSM thing as much as anything, but in case not:

Here in Chengdu, Chinese labels are largely absent at zoom levels <= 11, then from there on in, increasing zoom, it's mainly Chinese-characters-only up to ~17, where romanized labels start reappearing. 

http://maps.stamen.com/terrain/beta/#11/30.6586/104.0567

**Comment by geoglrb** [comment]
Here may be some more useful clues:

Neither the city of Chengdu (lower right in first image below) nor the city of Dujiangyan (upper left in first image below) are labeled in either of these two zoom levels below. In the second, you do get something in the proximity of Dujiangyan, but labeled by the name of Guankou. There are a few oblique references to this toponym buried in the records I'm looking at, but this is not the name of the city nor a good label.
See:
https://nominatim.openstreetmap.org/details.php?place_id=630162 
https://en.wikipedia.org/wiki/Dujiangyan_City

<img width="717" alt="screen shot 2016-07-11 at 2 25 28 pm" src="https://cloud.githubusercontent.com/assets/6434485/16747532/50d8ba50-4774-11e6-8f6e-3cd24bc80cd5.png">


<img width="500" alt="screen shot 2016-07-11 at 2 30 02 pm" src="https://cloud.githubusercontent.com/assets/6434485/16747524/4d4666ee-4774-11e6-91c9-37e3f714050c.png">

**Comment by geoglrb** [comment]
Also a lot of less-than-ideal landform shading... at certain zoom levels, gets pretty discrete in the pixelated steps that become visible...

**Comment by geoglrb** [comment]
All that said, the relations of labels to administrative hierarchies in Seattle area is also non-obvious to me...so maybe it's just me!
<img width="794" alt="screen shot 2016-07-11 at 2 36 17 pm" src="https://cloud.githubusercontent.com/assets/6434485/16747677/fe9f9d16-4774-11e6-9230-7b7bfd69de0e.png">

**Comment by clhenrick** [comment]
@geoglrb thanks for pointing out these various issues. In the future when creating Github issues please only open one issue per specific subject. 

Closing to break this out into multiple issues.
