### ISSUE TITLE
Land cover

### ISSUE THREAD

**Issue by geoglrb** [stamen/terrain-classic#77]
Not sure this count as an 'issue', but throwing it out there:

<img width="623" alt="screen shot 2016-07-11 at 2 41 58 pm" src="https://cloud.githubusercontent.com/assets/6434485/16748332/4b694a22-4778-11e6-9202-5f45b038ecba.png">

It just strikes me as something I've never seen to have Tibet, Northeastern China, and the area outside Shanghai all shaded similarly, whereas certain...highly forested areas?...are differentiated so strongly from these three (very different, in terms of land use and land cover) regions.

**Comment by clhenrick** [comment]
@geoglrb the land cover data we are using comes from [MODIS](http://glcf.umd.edu/data/lc/). The lighter values in the areas you are pointing out are "barren or sparsely vegetated", "grasslands", and "croplands"; these values are shared among the three geographic areas you pointed out, while the two darker green areas are "mixed forest" and "woody savannas." We are trying to keep the color range of the palette for the landcover within a earthy color scheme and used the original Stamen Terrain's color scheme as a source of inspiration. 

We're happy to hear thoughts are improving the color palette while keeping within the style of the original terrain tiles. If you have a palette you'd like to suggest please feel free to email it to us at openterrain@stamen.com.

**Comment by geoglrb** [comment]
Just saying that the result doesn't make too much sense. Procedurally, I can see how you get there. It just isn't going to be as useful to as many people as you might hope, at present...

**Comment by geoglrb** [comment]
I suppose the questions are: what is a beta test, what is a bug, etc.

**Comment by geoglrb** [comment]
One possible change: Bring MODIS codes 10, 12, 14 closer in shade to 3-4 than to 16. Not sure if having 12 and 16 be the same color fits much with what I interpret to be the median geographic imagination.

**Comment by mojodna** [comment]
What _is_ a bug...? How existential.

Your feedback is definitely appreciated. We're finding ourselves encountering the "what is a beta test" question as well. In truth, this was more of a preview, though we do hope to address feedback to whatever extent we can, given time.

**Comment by geoglrb** [comment]
Thanks, Seth! I do love the project, and I know tastes and purposes will invariably differ.

**Comment by geoglrb** [comment]
So, just to follow up once more on the suggestion above... Not that vegetation indices are what need drive the cartography, but it's interesting:

![756338main_npp-vegetation-map-673](https://cloud.githubusercontent.com/assets/6434485/16756436/e1c7e492-47b9-11e6-834c-9a437163b94c.jpg)

Above is a yearly average vegetation index from Suomi NPP. Below is a MODIS landcover product. 

![global_veg](https://cloud.githubusercontent.com/assets/6434485/16756489/5083304e-47ba-11e6-93df-c6888497d9d1.jpg)

Croplands, at the least, seem pretty green. Grasslands are a more marginal case... etc.
