### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by evejweinberg** [stamen/terrain-classic#79]
Not sure what the actual issue is, but the console log says this:

Mixed Content: The page at 'https://maps.stamen.com/terrain/beta/?' was loaded over HTTPS, but requested an insecure script 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js'. This request has been blocked; the content must be served over HTTPS.
maptiks-leaflet.min.js:1 

Uncaught TypeError: Cannot read property 'Map' of undefined(anonymous function) @ maptiks-leaflet.min.js:1(anonymous function) @ maptiks-leaflet.min.js:1(anonymous function) @ maptiks-leaflet.min.js:1
common.js?recaptcha:477 

Uncaught ReferenceError: L is not defined(anonymous function) @ common.js?recaptcha:477
maps.stamen.com/:12 

Mixed Content: The page at 'https://maps.stamen.com/terrain/beta/?' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css'. This request has been blocked; the content must be served over HTTPS.
layer.js?20130425:11 

Uncaught ReferenceError: L is not definedgetSize @ layer.js?20130425:11init @ layer.js?20130425:15(anonymous function) @ layer.js?20130425:159(anonymous function) @ layer.js?20130425:161

**Comment by mojodna** [comment]
We accidentally sent out a link with HTTPS in it. We definitely should support HTTPS in the (near) future, but we'll make sure to link to the HTTP version in the meantime.
