### ISSUE TITLE
Make labels only

### ISSUE THREAD

**Issue by smathermather** [stamen/terrain-classic#8]
Any plans to create a ```make``` for labels only? If not, any pointers for doing so? I just painstakingly made everything but labels transparent, which is a poor hack... .

**Comment by almccon** [comment]
Yeah, I'd like to make one. 

Right now I'm just copying patterns from the toner-carto repo, so doing whatever we do there should basically work here.

**Comment by almccon** [comment]
I added a path in `tessera.json` to enable the labels-only style. Is that what you're looking for?

![screen shot 2015-06-26 at 3 11 52 pm](https://cloud.githubusercontent.com/assets/1212178/8388340/ba085034-1c15-11e5-831d-71c5b6f04ef4.png)

**Comment by smathermather** [comment]
Ahhh, yes. That will do the trick. Nice screen shot.

**Comment by smathermather** [comment]
Saved me today. My version with transparency set was taking much longer to render. Reran with this. Thanks!
