### ISSUE TITLE
Few missing hillshade & landcover tiles

### ISSUE THREAD

**Issue by ungarj** [stamen/terrain-classic#82]
Missing landcover:

Austria: http://maps.stamen.com/terrain/beta/#12/47.7319/13.4833
Izmir: http://maps.stamen.com/terrain/beta/#7/40.718/26.724

Missing hillshade in Teheran:
http://maps.stamen.com/terrain/beta/#7/35.934/52.064

**Comment by mojodna** [comment]
Good eye, thank you for spotting these. They've been removed from S3 and will be re-rendered (unless they've already been re-rendered).

In theory the style is self-healing, as it will invalidate tiles where an upstream error occurred (missing tiles being composited together) to be re-rendered on the next request. However, it appears that S3 occasionally returns 404 when it's supposed to redirect, and those are treated as "successful" (despite containing no data), leading to busted, cached tiles like you spotted.
