### ISSUE TITLE
Mixed content on the HTTPS beta site.

### ISSUE THREAD

**Issue by mejackreed** [stamen/terrain-classic#83]
When referencing the HTTPS version of the beta site, it uses the Leaflet CDN that only works over HTTP unfortunately. This will cause an error on the page, and the JavaScript will not load.

Potentially use the updated npmjs cdn `https://npmcdn.com/leaflet@0.7.7/dist/leaflet.js` from: http://leafletjs.com/download.html

Or the cdnjs version: https://cdnjs.com/libraries/leaflet/

**Comment by mojodna** [comment]
We accidentally sent the link out as HTTPS. We intend to support HTTPS at some point, but we're not there yet. For now, just refer to the HTTP version of the site.

Thanks!
