### ISSUE TITLE
Terrain-Beta Web Map load issues with mixed content for leaflet

### ISSUE THREAD

**Issue by gisdev-km** [stamen/terrain-classic#84]
The leaflet.js and .css is trying to load via http instead of https which Chrome blocks due to mixed content ; leaflet then fails and no maps are shown.

[Screenshot](http://imgur.com/a/GJ7eU)

**Comment by mojodna** [comment]
We accidentally sent an HTTPS link out in the email. We do intend to support HTTPS at some point, but not immediately.
