### ISSUE TITLE
Bizarre coloring for estuarine sanctuary at zoom level 15

### ISSUE THREAD

**Issue by clayheaton** [stamen/terrain-classic#87]
The Rachel Carson Estuarine Sanctuary, in Beaufort, NC, is drawn with a green block around it when at zoom level 15, but not at other zoom levels. The terrain is tricky in that region - lots of wetlands.

http://maps.stamen.com/terrain/#15/34.7044/-76.6351

![screen shot 2016-07-22 at 2 52 10 pm](https://cloud.githubusercontent.com/assets/205364/17067877/e4197228-501b-11e6-8480-db1721403271.png)

Google Maps satellite view:

![screen shot 2016-07-22 at 2 53 16 pm](https://cloud.githubusercontent.com/assets/205364/17067919/0f8d9a24-501c-11e6-90d0-7f7532c3ef00.png)

and map view:

![screen shot 2016-07-22 at 2 53 43 pm](https://cloud.githubusercontent.com/assets/205364/17067933/1cbfe15c-501c-11e6-8bbb-8e414da72279.png)

**Comment by clhenrick** [comment]
Looks like a tile mis-render: http://a.tile.stamen.com/terrain/15/9408/13012.png

![screen shot 2016-07-22 at 5 41 30 pm](https://cloud.githubusercontent.com/assets/161748/17074706/9a62ff38-5033-11e6-9cd1-696f770f6a57.png)

cc @mojodna

**Comment by mojodna** [comment]
Yup. Fixed: http://tile.stamen.com.s3.amazonaws.com/terrain/15/9408/13012.png

(It's possible to trigger a re-render of an individual tile by using a URL similar to http://a.dyn.tile.stamen.com/terrain/15/9408/13012.png)

The busted tile is still cached by the CDN for now, but that too shall pass.

**Comment by mojodna** [comment]
Thanks @clayheaton!
