### ISSUE TITLE
buildings are way too blue

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#9]
previous:
![screen shot 2015-06-26 at 3 13 36 pm](https://cloud.githubusercontent.com/assets/1212178/8388360/f59def46-1c15-11e5-9a72-9396dc63954f.png)
currently:
![screen shot 2015-06-26 at 3 13 33 pm](https://cloud.githubusercontent.com/assets/1212178/8388361/f5af0f24-1c15-11e5-951d-f4b406d39a23.png)

**Comment by clhenrick** [comment]
Closing for now
![screen shot 2015-08-31 at 2 05 11 pm](https://cloud.githubusercontent.com/assets/161748/9586213/6be278dc-4fe9-11e5-9c19-e50728c45950.png)
