### ISSUE TITLE
Wrong tile

### ISSUE THREAD

**Issue by mramazing01** [stamen/terrain-classic#95]
![maps](https://cloud.githubusercontent.com/assets/19423749/18207539/723c962a-7123-11e6-88e6-b50e21f4c943.png)

http://maps.stamen.com/terrain/#8/46.796/15.271

Wrong map tile.

Many thanks,

**Comment by mojodna** [comment]
Thanks. I manually re-generated that tile, so once it falls out of the CDN's cache, all should be well again.
