### ISSUE TITLE
Missing roads tile in Redmond, WA?

### ISSUE THREAD

**Issue by gfwellman** [stamen/terrain-classic#99]
http://maps.stamen.com/terrain/embed#15/47.6602/-122.1325
Just below the words "Westside Park" there's a tile that isn't showing roads and buildings, but if you zoom in one level, they show up.  Ironically, I think that partly obliterates a portion of the Microsoft campus.

**Comment by clhenrick** [comment]
Thanks for letting us know @gfwellman, I'm not seeing this:

![screen shot 2016-11-05 at 11 49 54 am](https://cloud.githubusercontent.com/assets/161748/20032728/241ef494-a34e-11e6-8a85-b8706a396df7.png)

Same zoom and map center on default OSM:

![screen shot 2016-11-05 at 11 49 54 am](https://cloud.githubusercontent.com/assets/161748/20032730/342aa7c0-a34e-11e6-99e8-4714d428a0bf.png)

When tiles for an are cached for the first time sometimes one or two can fail to load. They should load the next time they are requested which is what I'm assuming you experienced.

**Comment by almccon** [comment]
<img width="860" alt="screen shot 2016-11-05 at 5 nov 2 04 06" src="https://cloud.githubusercontent.com/assets/1212178/20033580/ce749dce-a360-11e6-8217-d797490fd287.png">

It's happening to me. However, I agree that this is just a temporary caching issue and it should fix itself automatically.

Here's the relevant tile that fails (on Retina):
http://a.tile.stamen.com/terrain/15/5267/11437@2x.png

But the non-retina version works:
http://a.tile.stamen.com/terrain/15/5267/11437.png

**Comment by clhenrick** [comment]
@almccon I didn't check retina tiles for this area, thanks.

@mojodna do you know if the tile fail error handling was implemented for retina tiles? It doesn't seem to be re-rendering for the particular tile mentioned above.

**Comment by mojodna** [comment]
@clhenrick it is. http://a.dyn.tile.stamen.com/terrain/15/5267/11437@2x.png re-generated it.

**Comment by clhenrick** [comment]
@mojodna, thanks, that URL isn't pinged by default though correct?

**Comment by mojodna** [comment]
It is when the (retina) tile doesn't exist. It's part of the redirect chain (and is the API Gateway endpoint).
